#!/bin/bash
set -eu -o pipefail

if [[ ! -e "$HOME/.kube" ]]; then
  mkdir "$HOME/.kube"
fi
if [[ ! -e "$HOME/.oci" ]]; then
  mkdir "$HOME/.oci"
fi
if [[ ! -e "$HOME/suggestion_variable.txt" ]]; then
  touch "$HOME/suggestion_variable.txt"
fi

if command -v docker &>/dev/null; then
  # shellcheck disable=SC2046
  docker container run \
    --name oci$$ \
    --rm \
    -e HOME="$HOME" \
    -e USER_NAME="$(id -un)" \
    -i \
    -t \
    -u "$(id -u):$(id -g)" \
    -v "$HOME/.kube:$HOME/.kube" \
    -v "$HOME/.oci:$HOME/.oci" \
    -v "$HOME/suggestion_variable.txt:$HOME/suggestion_variable.txt" \
    $([[ -v OCI_CLI_PROFILE ]] && echo "-e OCI_CLI_PROFILE=$OCI_CLI_PROFILE") \
    $([[ -v SUPPRESS_LABEL_WARNING ]] && echo "-e SUPPRESS_LABEL_WARNING=$SUPPRESS_LABEL_WARNING") \
    ghcr.io/shakiyam/oci-cli "$@"
elif command -v podman &>/dev/null; then
  # shellcheck disable=SC2046
  podman container run \
    --entrypoint=/usr/local/bin/oci \
    --name oci$$ \
    --rm \
    --security-opt label=disable \
    --userns=keep-id \
    -e HOME="$HOME" \
    -i \
    -t \
    -v "$HOME/.kube:$HOME/.kube" \
    -v "$HOME/.oci:$HOME/.oci" \
    -v "$HOME/suggestion_variable.txt:$HOME/suggestion_variable.txt" \
    $([[ -v OCI_CLI_PROFILE ]] && echo "-e OCI_CLI_PROFILE=$OCI_CLI_PROFILE") \
    $([[ -v SUPPRESS_LABEL_WARNING ]] && echo "-e SUPPRESS_LABEL_WARNING=$SUPPRESS_LABEL_WARNING") \
    ghcr.io/shakiyam/oci-cli "$@"
else
  echo "Neither docker nor podman is installed."
  exit 1
fi
