#!/bin/bash
set -eu -o pipefail

if [[ ! -e "$HOME/.oci" ]]; then
  mkdir "$HOME/.oci"
fi

if [[ $(command -v docker) ]]; then
  docker container run \
    --name oci$$ \
    --rm \
    -e HOME="$HOME" \
    -e USER_NAME="$(id -un)" \
    -i \
    -t \
    -u "$(id -u):$(id -g)" \
    -v "$HOME/.oci:$HOME/.oci" \
    $([[ -v OCI_CLI_PROFILE ]] && echo "-e OCI_CLI_PROFILE=$OCI_CLI_PROFILE") \
    docker.io/shakiyam/oci-cli "$@"
else
  podman container run \
    --entrypoint=/usr/local/bin/oci \
    --name oci$$ \
    --rm \
    --security-opt label=disable \
    --userns=keep-id \
    -e HOME="$HOME" \
    -i \
    -t \
    -v "$HOME/.oci:$HOME/.oci" \
    $([[ -v OCI_CLI_PROFILE ]] && echo "-e OCI_CLI_PROFILE=$OCI_CLI_PROFILE") \
    docker.io/shakiyam/oci-cli "$@"
fi
